### PR TITLE
initial implementation

### PR DESCRIPTION
**Pull request by notwaldorf**
I am not really sure how to test this -- the demo was a struggle too :)

### CODE REVIEW

**Comment by notwaldorf** [comment]
ping?

**Comment by morethanreal** [comment]
I think this should be a `IronFormElementBehavior` and the `simple-form` demo made into `IronFormBehavior`.

**Comment by morethanreal** [comment]
It also seems like the form should have more features like collecting the name/value pairs for all the form elements, and a way to submit it (maybe serialize into JSON). It should work with native form elements where possible as well as elements using `IronFormElementBehavior`.

**Comment by notwaldorf** [comment]
Done! Offline chat TL; DR: this is just the "track this element in a form" behaviour. The actual form with all the magic is `iron-form`

**Comment by notwaldorf** [comment]
(I will rename the repo after this gets merged)

**Comment by notwaldorf** [comment]
moar ping? :)

**Comment by morethanreal** [comment]
lgtm

**Pull request merged**
