### PR TITLE
Switch on Polymer.Element in a way that Analyzer understands.

### PR DESCRIPTION
**Pull request by aomarks**
I'm not sure if this is actually correct, so please let me know. Is there some reason we need to set attached to `null` rather than a no-op function? The existing code confuses Analyzer and hence makes type declarations that are incompatible with Polymer.Element.

### CODE REVIEW

**Review by valdrinkoshi — COMMENTED** [review]
The reason was to not have these methods being called in 2.x, for an hypothetical performance gain. Would it still confuse the analyzer if we set them to `undefined` instead of `null`? or if we conditionally define these methods e.g.
```js
Polymer.IronFormElementBehavior = {
 //...
};

if (!Polymer.Element) {
  Polymer.IronFormElementBehavior.attached = function() {
    //...
```
If neither is an option or it looks like over engineering, let's just do the no-op, anyways this behavior is deprecated in 2.x

The only change I'd ask is to declare the attached/detached as `attached: function() {}`

**Comment by aomarks** [comment]
> The only change I'd ask is to declare the attached/detached as attached: function() {}

Actually, only the style currently in the PR is understood by Analyzer. It only knows to look for a direct function declaration. It cannot currently reason e.g. that if both cases of a ternary are the same type, then it is that type.

See this Analyzer playground link for a bunch of variations I tried, including some attempts to force it with annotations (click on raw analysis and see that only `attachedA` produces a method, everything else is a wrongly-typed property):

https://polymer.github.io/analyzer-playground/?input=%3Cscript%3E%0A++%2F**%0A++%40polymerBehavior%0A++*%2F%0A++Polymer.IronFormElementBehavior+%3D+%7B%0A++++attachedA%28%29+%7B%0A++++++if+%28%21Polymer.Element%29+%7B%0A++++++++this.fire%28%27iron-form-element-register%27%29%3B%0A++++++%7D%0A++++%7D%2C%0A++++%0A++++attachedB%3A+Polymer.Element+%3F+null+%3A+function%28%29+%7B%0A++++++this.fire%28%27iron-form-element-register%27%29%3B%0A++++%7D%2C%0A%0A++++attachedC%3A+Polymer.Element+%3F+function%28%29+%7B%7D+%3A+function%28%29+%7B%0A++++++this.fire%28%27iron-form-element-register%27%29%3B%0A++++%7D%2C%0A%0A++++%2F**+%40method+*%2F%0A++++attachedD%3A+Polymer.Element+%3F+null+%3A+function%28%29+%7B%0A++++++this.fire%28%27iron-form-element-register%27%29%3B%0A++++%7D%2C%0A%0A++++%2F**+%40private+*%2F%0A++++attachedE%3A+Polymer.Element+%3F+null+%3A+function%28%29+%7B%0A++++++this.fire%28%27iron-form-element-register%27%29%3B%0A++++%7D%2C%0A%0A++%7D%3B%0A%3C%2Fscript%3E

**Comment by aomarks** [comment]
> if (!Polymer.Element) {
>   Polymer.IronFormElementBehavior.attached = function() {
>     //...

Oh, actually I think this style you suggested would work, because I think Analyzer won't understand it at all. (Which is fine, because the problem motivating this change is that when an element applies both this and some other behavior, unless the property types match exactly, there will be a compile error).

**Comment by aomarks** [comment]
> Oh, actually I think this style you suggested would work, because I think Analyzer won't understand it at all. (Which is fine, because the problem motivating this change is that when an element applies both this and some other behavior, unless the property types match exactly, there will be a compile error).

Tried this out, but it's difficult to get Closure happy with `this` in the function. We can add a `@this` annotation, but Closure does not seem to be aware of a `Polymer.IronFormElementBehavior` type, so it's not clear what would be the right parameter to `this`.

**Review by valdrinkoshi — APPROVED** [review]
LGTM modulo green tests & resolved conflicts 👌

**Pull request merged**
